### ISSUE TITLE
using Encoder ForModel(string modelName)

### ISSUE THREAD

**Issue by Xan-Kun** [tryAGI/Tiktoken#30]
## What would you like to be added:
The ability to get an Encoder directly from the model name.
Ideally, we provide "gpt-4-0613" and get back the correct encoder.
Should also work with older models.
Basically using the same info as
https://github.com/dotnet/machinelearning/blob/4d5317e8090e158dc7c3bc6c435926ccf1cbd8e2/src/Microsoft.ML.Tokenizers/Model/Tiktoken.cs#L683-L734

## Why is this needed:
There seems to be code already dedicated to this, and EncoderHelpers.ForModel(string modelName) is public, but EncoderHelpers is internal. This means there is no direct way to use this method.

## Anything else we need to know?
(Slightly off-topic :-) )
Great library!! Thank you so much.
Exactly what we need in our project, super minimal and good depedencies, unlike the "official" Microsoft.ML.Tokenizer which needs their strange and unpopular System.Text.Json and Google.protobuf (?!). No thanks :-))
And they STILL (it's almost a week now) havent added omni 🤣
Keep up the great work 👍

**Comment by HavenDV** [comment]
Thank you. I added `ModelToEncoder.For("gpt-4o")` in the latest version

**Comment by Xan-Kun** [comment]
Works perfectly.
Thanks!
